export const ALGORITHMS_CODE_LABS = [
  // --- bloom-filter ---
  {
    id: 'bloom-hash-index',
    stepLabel: '70.1',
    group: 'Hash positions',
    title: 'Bloom Filter Hash Function',
    concept: 'Bloom filters use multiple hash functions to map items to bit array indices.',
    objective: 'Compute the bit index for a string item using a simple seeded hash: sum(charCodes[i] * seed) % size.',
    difficulty: 'warmup',
    starterCode: `function getBloomHash(item, seed, size) {
  let hash = 0;
  for (let i = 0; i < item.length; i++) {
    // TODO: multiply charCode by seed and accumulate in hash
    hash += 0;
  }
  return hash % size;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: Object.is(actual, expected) });
}
check('hash test 1', getBloomHash('apple', 31, 100), 30);
check('hash test 2', getBloomHash('banana', 17, 100), 53);
return results;`,
    hints: [
      'Use item.charCodeAt(i) to get the character code.',
      'Multiply by seed and add to hash.',
      'hash += item.charCodeAt(i) * seed;',
    ],
    solution: `function getBloomHash(item, seed, size) {
  let hash = 0;
  for (let i = 0; i < item.length; i++) {
    hash += item.charCodeAt(i) * seed;
  }
  return hash % size;
}`,
    explanation: 'A seeded hash function maps arbitrary strings to bounded integer indices deterministically.',
  },
  {
    id: 'bloom-insert-item',
    stepLabel: '70.2',
    group: 'Hash positions',
    title: 'Bloom Filter Insertion',
    concept: 'Inserting an item into a Bloom filter sets the bits at all computed hash positions to 1.',
    objective: 'Modify the bit array in-place by setting bits at the positions generated by the seeds.',
    difficulty: 'core',
    starterCode: `function bloomInsert(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    // TODO: set the bit at idx in bitArray to 1
  }
}`,
    testCode: `const results = [];
function sameArr(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
function check(name, actual, expected) {
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed: sameArr(actual, expected) });
}
const bits = Array(10).fill(0);
bloomInsert(bits, 'abc', [5, 9]);
check('bits set after insert', bits, [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]);
return results;`,
    hints: [
      'Set bitArray[idx] = 1.',
    ],
    solution: `function bloomInsert(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    bitArray[idx] = 1;
  }
}`,
    explanation: 'Setting bits for multiple independent hashes overlays membership signatures in the shared bit array.',
  },
  {
    id: 'bloom-maybe-contains',
    stepLabel: '70.3',
    group: 'Query all bits',
    title: 'Bloom Filter Query',
    concept: 'A Bloom filter queries membership by checking if all hash positions are set to 1. If any is 0, the item is definitely not in the set.',
    objective: 'Verify if the item is present in the Bloom filter.',
    difficulty: 'challenge',
    starterCode: `function bloomContains(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    // TODO: if bitArray[idx] is 0, return false
  }
  return true;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: Object.is(actual, expected) });
}
const bits = [1, 0, 0, 0, 0, 0, 1, 0, 0, 0];
check('should contain abc', bloomContains(bits, 'abc', [5, 9]), true);
check('should not contain xyz', bloomContains(bits, 'xyz', [5, 9]), false);
return results;`,
    hints: [
      'Check if bitArray[idx] === 0. If so, return false.',
    ],
    solution: `function bloomContains(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    if (bitArray[idx] === 0) {
      return false;
    }
  }
  return true;
}`,
    explanation: 'A zero bit guarantees non-membership; all ones indicate membership, subject to false positive probabilities.',
  },

  // --- pagerank ---
  {
    id: 'pagerank-share',
    stepLabel: '71.1',
    group: 'PageRank iteration',
    title: 'Out-link share',
    concept: 'Each page distributes rank equally across outgoing links.',
    objective: 'Compute share = rank / outDegree for non-dangling pages.',
    difficulty: 'warmup',
    starterCode: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) continue;
    // TODO: share and distribute
  }
  return next;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: Object.is(actual, expected) });
}
const out = pagerankStep([0.6, 0.4], [[1], [0,1]], 0.85);
check('share effect', out[1] > out[0], true);
return results;`,
    hints: ['const share = ranks[j] / out.length;'],
    solution: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) continue;
    const share = ranks[j] / out.length;
    for (let i = 0; i < out.length; i++) next[out[i]] += share;
  }
  return next;
}`,
    explanation: 'Rank mass conservation is the base PageRank mechanism.',
  },
  {
    id: 'pagerank-dangling',
    stepLabel: '71.2',
    group: 'PageRank iteration',
    title: 'Dangling node redistribution',
    concept: 'Pages with no links spread mass uniformly to all pages.',
    objective: 'Handle out.length===0 by adding ranks[j]/n to all nodes.',
    difficulty: 'warmup',
    starterCode: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      // TODO: distribute dangling mass equally
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  return next;
}`,
    testCode: `const results = [];
function approxEqual(a, b, tol = 1e-9) { return Math.abs(a - b) <= tol; }
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: approxEqual(actual, expected) });
}
const out = pagerankStep([1, 0], [[], [0]], 0.85);
check('dangling gives half', out[0], 0.5);
check('dangling gives half2', out[1], 0.5);
return results;`,
    hints: ['for (let i = 0; i < n; i++) next[i] += ranks[j] / n;'],
    solution: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  return next;
}`,
    explanation: 'Dangling handling prevents rank sink collapse.',
  },
  {
    id: 'pagerank-teleport',
    stepLabel: '71.3',
    group: 'PageRank iteration',
    title: 'Apply damping and teleport',
    concept: 'Damping blends random jump with link-following probability.',
    objective: 'Transform next[i] to d*next[i] + (1-d)/n.',
    difficulty: 'core',
    starterCode: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  // TODO: apply damping
  return next;
}`,
    testCode: `const results = [];
function same(a, b, tol = 1e-5) { return a.length === b.length && a.every((v, i) => Math.abs(v - b[i]) <= tol); }
function check(name, actual, expected) {
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed: same(actual, expected) });
}
check('pagerank example', pagerankStep([0.5, 0.5], [[1], [0,1]], 0.85), [0.2875, 0.7125]);
return results;`,
    hints: ['for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;'],
    solution: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;
  return next;
}`,
    explanation: 'Teleportation guarantees ergodicity and convergence.',
  },
  {
    id: 'pagerank-normalize',
    stepLabel: '71.4',
    group: 'PageRank iteration',
    title: 'Normalize numeric drift',
    concept: 'Finite precision can make rank sum deviate from 1.',
    objective: 'Normalize next by total sum.',
    difficulty: 'core',
    starterCode: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;
  // TODO: normalize next
  return next;
}`,
    testCode: `const results = [];
function approxEqual(a, b, tol = 1e-9) { return Math.abs(a - b) <= tol; }
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: approxEqual(actual, expected) });
}
const out = pagerankStep([0.5, 0.5], [[1], [0,1]], 0.85);
check('sum one', out[0] + out[1], 1);
return results;`,
    hints: ['const total = next.reduce((s, v) => s + v, 0); if (total > 0) divide each'],
    solution: `function pagerankStep(ranks, adjList, d) {
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;
  const total = next.reduce((s, v) => s + v, 0);
  if (total > 0) for (let i = 0; i < n; i++) next[i] /= total;
  return next;
}`,
    explanation: 'Normalization maintains probabilistic interpretation each iteration.',
  },
  {
    id: 'pagerank-iteration-step',
    stepLabel: '71.5',
    group: 'PageRank iteration',
    title: 'Complete PageRank iteration',
    concept: 'Final step combines distribution, damping, and normalization robustly.',
    objective: 'Return null when d is outside [0,1].',
    difficulty: 'core',
    starterCode: `function pagerankStep(ranks, adjList, d) {
  // TODO: validate damping range
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;
  const total = next.reduce((s, v) => s + v, 0);
  if (total > 0) for (let i = 0; i < n; i++) next[i] /= total;
  return next;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  const passed = JSON.stringify(actual) === JSON.stringify(expected);
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed });
}
check('invalid d', pagerankStep([0.5, 0.5], [[1], [0,1]], 1.2), null);
return results;`,
    hints: ['if (d < 0 || d > 1) return null;'],
    solution: `function pagerankStep(ranks, adjList, d) {
  if (d < 0 || d > 1) return null;
  const n = ranks.length;
  const next = Array(n).fill(0);
  for (let j = 0; j < n; j++) {
    const out = adjList[j];
    if (out.length === 0) {
      for (let i = 0; i < n; i++) next[i] += ranks[j] / n;
    } else {
      const share = ranks[j] / out.length;
      for (let i = 0; i < out.length; i++) next[out[i]] += share;
    }
  }
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) next[i] = d * next[i] + teleport;
  const total = next.reduce((s, v) => s + v, 0);
  if (total > 0) for (let i = 0; i < n; i++) next[i] /= total;
  return next;
}`,
    explanation: 'Validation plus complete update gives a production-safe iteration primitive.',
  },
];
