export const ALGORITHMS_CODE_LABS = [
  // --- bloom-filter ---
  {
    id: 'bloom-hash-index',
    stepLabel: '70.1',
    group: 'Hash positions',
    title: 'Bloom Filter Hash Function',
    concept: 'Bloom filters use multiple hash functions to map items to bit array indices.',
    objective: 'Compute the bit index for a string item using a simple seeded hash: sum(charCodes[i] * seed) % size.',
    difficulty: 'warmup',
    starterCode: `function getBloomHash(item, seed, size) {
  let hash = 0;
  for (let i = 0; i < item.length; i++) {
    // TODO: multiply charCode by seed and accumulate in hash
    hash += 0;
  }
  return hash % size;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: Object.is(actual, expected) });
}
check('hash test 1', getBloomHash('apple', 31, 100), 30);
check('hash test 2', getBloomHash('banana', 17, 100), 53);
return results;`,
    hints: [
      'Use item.charCodeAt(i) to get the character code.',
      'Multiply by seed and add to hash.',
      'hash += item.charCodeAt(i) * seed;',
    ],
    solution: `function getBloomHash(item, seed, size) {
  let hash = 0;
  for (let i = 0; i < item.length; i++) {
    hash += item.charCodeAt(i) * seed;
  }
  return hash % size;
}`,
    explanation: 'A seeded hash function maps arbitrary strings to bounded integer indices deterministically.',
  },
  {
    id: 'bloom-insert-item',
    stepLabel: '70.2',
    group: 'Hash positions',
    title: 'Bloom Filter Insertion',
    concept: 'Inserting an item into a Bloom filter sets the bits at all computed hash positions to 1.',
    objective: 'Modify the bit array in-place by setting bits at the positions generated by the seeds.',
    difficulty: 'core',
    starterCode: `function bloomInsert(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    // TODO: set the bit at idx in bitArray to 1
  }
}`,
    testCode: `const results = [];
function sameArr(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
function check(name, actual, expected) {
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed: sameArr(actual, expected) });
}
const bits = Array(10).fill(0);
bloomInsert(bits, 'abc', [5, 9]);
check('bits set after insert', bits, [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]);
return results;`,
    hints: [
      'Set bitArray[idx] = 1.',
    ],
    solution: `function bloomInsert(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    bitArray[idx] = 1;
  }
}`,
    explanation: 'Setting bits for multiple independent hashes overlays membership signatures in the shared bit array.',
  },
  {
    id: 'bloom-maybe-contains',
    stepLabel: '70.3',
    group: 'Query all bits',
    title: 'Bloom Filter Query',
    concept: 'A Bloom filter queries membership by checking if all hash positions are set to 1. If any is 0, the item is definitely not in the set.',
    objective: 'Verify if the item is present in the Bloom filter.',
    difficulty: 'challenge',
    starterCode: `function bloomContains(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    // TODO: if bitArray[idx] is 0, return false
  }
  return true;
}`,
    testCode: `const results = [];
function check(name, actual, expected) {
  results.push({ name, actual, expected, passed: Object.is(actual, expected) });
}
const bits = [1, 0, 0, 0, 0, 0, 1, 0, 0, 0];
check('should contain abc', bloomContains(bits, 'abc', [5, 9]), true);
check('should not contain xyz', bloomContains(bits, 'xyz', [5, 9]), false);
return results;`,
    hints: [
      'Check if bitArray[idx] === 0. If so, return false.',
    ],
    solution: `function bloomContains(bitArray, item, seeds) {
  const size = bitArray.length;
  for (let s = 0; s < seeds.length; s++) {
    const seed = seeds[s];
    let hash = 0;
    for (let i = 0; i < item.length; i++) {
      hash += item.charCodeAt(i) * seed;
    }
    const idx = hash % size;
    if (bitArray[idx] === 0) {
      return false;
    }
  }
  return true;
}`,
    explanation: 'A zero bit guarantees non-membership; all ones indicate membership, subject to false positive probabilities.',
  },

  // --- pagerank ---
  {
    id: 'pagerank-distribute-mass',
    stepLabel: '71.1',
    group: 'Out-link normalize',
    title: 'PageRank Mass Distribution',
    concept: 'PageRank spreads page importance (rank) across outgoing link connections.',
    objective: 'Add the distributed PageRank mass from source to target pages.',
    difficulty: 'warmup',
    starterCode: `function distributeRank(sourceRank, outLinks, targetRanks) {
  if (outLinks.length === 0) return;
  const share = sourceRank / outLinks.length;
  for (let i = 0; i < outLinks.length; i++) {
    const targetIdx = outLinks[i];
    // TODO: add share to targetRanks[targetIdx]
    targetRanks[targetIdx] += 0;
  }
}`,
    testCode: `const results = [];
function sameArr(a, b, tol=1e-5) { return a.every((v, i) => Math.abs(v - b[i]) <= tol); }
function check(name, actual, expected) {
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed: sameArr(actual, expected) });
}
const targets = [0, 0, 0];
distributeRank(1.2, [0, 2], targets);
check('mass distributed', targets, [0.6, 0.0, 0.6]);
return results;`,
    hints: [
      'Add share to targetRanks[targetIdx].',
      'targetRanks[targetIdx] += share;',
    ],
    solution: `function distributeRank(sourceRank, outLinks, targetRanks) {
  if (outLinks.length === 0) return;
  const share = sourceRank / outLinks.length;
  for (let i = 0; i < outLinks.length; i++) {
    const targetIdx = outLinks[i];
    targetRanks[targetIdx] += share;
  }
}`,
    explanation: 'PageRank mass is divided equally among a page\'s outward pointing links, representing a random web surfer\'s choices.',
  },
  {
    id: 'pagerank-power-iteration',
    stepLabel: '71.2',
    group: 'Damping teleport',
    title: 'PageRank Power Iteration Step',
    concept: 'PageRank updates combine link mass with a damping teleport factor: PR(i) = (1-d)/N + d * sum_j (PR(j)/L(j)).',
    objective: 'Compute the PageRank scores after one step of power iteration.',
    difficulty: 'core',
    starterCode: `function pagerankStep(ranks, adjList, d = 0.85) {
  const n = ranks.length;
  const nextRanks = Array(n).fill(0);
  
  // Distribute rank mass from links
  for (let j = 0; j < n; j++) {
    const outLinks = adjList[j];
    if (outLinks.length === 0) {
      // Dangling page: distribute equally to all pages
      for (let i = 0; i < n; i++) {
        nextRanks[i] += ranks[j] / n;
      }
    } else {
      const share = ranks[j] / outLinks.length;
      for (let i = 0; i < outLinks.length; i++) {
        nextRanks[outLinks[i]] += share;
      }
    }
  }
  
  // Apply damping factor
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) {
    // TODO: scale nextRanks[i] by d, and add teleport
    nextRanks[i] = 0;
  }
  
  return nextRanks;
}`,
    testCode: `const results = [];
function sameArr(a, b, tol=1e-5) { return a.every((v, i) => Math.abs(v - b[i]) <= tol); }
function check(name, actual, expected) {
  results.push({ name, actual: JSON.stringify(actual), expected: JSON.stringify(expected), passed: sameArr(actual, expected) });
}
const adj = [
  [1],
  [0, 1],
];
const initRanks = [0.5, 0.5];
check('pagerank iteration step', pagerankStep(initRanks, adj, 0.85), [0.2875, 0.7125]);
return results;`,
    hints: [
      'Scale the accumulated link mass by d, then add teleport.',
      'nextRanks[i] = d * nextRanks[i] + teleport;',
    ],
    solution: `function pagerankStep(ranks, adjList, d = 0.85) {
  const n = ranks.length;
  const nextRanks = Array(n).fill(0);
  
  for (let j = 0; j < n; j++) {
    const outLinks = adjList[j];
    if (outLinks.length === 0) {
      for (let i = 0; i < n; i++) {
        nextRanks[i] += ranks[j] / n;
      }
    } else {
      const share = ranks[j] / outLinks.length;
      for (let i = 0; i < outLinks.length; i++) {
        nextRanks[outLinks[i]] += share;
      }
    }
  }
  
  const teleport = (1 - d) / n;
  for (let i = 0; i < n; i++) {
    nextRanks[i] = d * nextRanks[i] + teleport;
  }
  
  return nextRanks;
}`,
    explanation: 'Teleportation represents a surfer typing a random URL, ensuring convergence stability in disconnected web graphs.',
  }
];
