export const OMNI_PRESETS = [
  {
    id: 'image-chat',
    label: 'Image + text chat',
    detail: 'One image and a short text prompt, text output only.',
    textTokens: 96,
    imageWidth: 448,
    imageHeight: 448,
    imagePatchSize: 14,
    videoSeconds: 0,
    videoFps: 0,
    audioSeconds: 0,
    audioFrameMs: 20,
    audioCodebooks: 1,
    speechSeconds: 0,
  },
  {
    id: 'video-audio',
    label: 'Video + audio question',
    detail: 'Time-aligned sampled video frames plus acoustic frames.',
    textTokens: 72,
    imageWidth: 336,
    imageHeight: 336,
    imagePatchSize: 14,
    videoSeconds: 8,
    videoFps: 2,
    audioSeconds: 8,
    audioFrameMs: 40,
    audioCodebooks: 1,
    speechSeconds: 0,
  },
  {
    id: 'voice-omni',
    label: 'Streaming voice response',
    detail: 'Audio input with concurrent text reasoning and speech-codec output.',
    textTokens: 48,
    imageWidth: 0,
    imageHeight: 0,
    imagePatchSize: 14,
    videoSeconds: 0,
    videoFps: 0,
    audioSeconds: 6,
    audioFrameMs: 20,
    audioCodebooks: 1,
    speechSeconds: 4,
  },
];

export const OMNI_DEFAULTS = {
  presetId: 'video-audio',
  fusionQueries: 32,
  speechFrameMs: 20,
  speechCodebooks: 8,
};
