import React, { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, RefreshCw, Sigma } from 'lucide-react';
import AssessmentPanel from '../../components/animation-shell/AssessmentPanel';
import { VALUE_ITERATION_DEFAULTS, VALUE_ITERATION_MDP } from './valueIterationConfig';
import { buildValueIterationLab } from './valueIterationModel';
function Stat({ label, value, detail }) { return <div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><strong className="mt-1 block text-2xl font-black text-slate-950">{value}</strong><span className="text-sm text-slate-600">{detail}</span></div>; }
export default function ValueIterationAnimation() {
  const [gamma, setGamma] = useState(VALUE_ITERATION_DEFAULTS.gamma); const [tolerance, setTolerance] = useState(VALUE_ITERATION_DEFAULTS.tolerance); const [visibleSweeps, setVisibleSweeps] = useState(VALUE_ITERATION_DEFAULTS.visibleSweeps);
  const lab = useMemo(() => buildValueIterationLab({ model: VALUE_ITERATION_MDP, gamma, tolerance, maxIterations: VALUE_ITERATION_DEFAULTS.maxIterations, visibleSweeps }), [gamma, tolerance, visibleSweeps]); const maxVisibleSweep = Math.min(20, lab.history.length - 1);
  return <div className="space-y-6">
    <section className="rounded-lg border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-indigo-700">Planning with a known MDP</p><h2 className="mt-1 text-2xl font-black text-slate-950">Value Iteration: repeated Bellman optimality backups</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-700">Each synchronous sweep uses the <em>previous</em> value table, keeps the best action value, and repeats until the Bellman residual is small. Terminal Goal has value 0 after its entry reward has been paid.</p></section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm font-bold text-slate-700">Discount γ: {gamma.toFixed(2)}<input type="range" min="0" max="0.99" step="0.01" value={gamma} onChange={(event) => setGamma(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold text-slate-700">Visible sweep: {Math.min(visibleSweeps, maxVisibleSweep)}<input type="range" min="0" max={maxVisibleSweep} step="1" value={Math.min(visibleSweeps, maxVisibleSweep)} onChange={(event) => setVisibleSweeps(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-bold text-slate-700">Tolerance: {tolerance}<select value={tolerance} onChange={(event) => setTolerance(Number(event.target.value))} className="rounded-lg border border-slate-300 px-3 py-2"><option value={0.01}>1e-2</option><option value={0.001}>1e-3</option><option value={0.0001}>1e-4</option><option value={0.000001}>1e-6</option></select></label></div></section>
    <div className="grid gap-3 md:grid-cols-4"><Stat label="Converged" value={lab.converged ? 'yes' : 'no'} detail={`${lab.history.length - 1} sweeps used`} /><Stat label="Final residual" value={lab.residual.toExponential(2)} detail="max |T*V − V|" /><Stat label="Visible residual" value={lab.visibleResidual.toExponential(2)} detail={`after sweep ${lab.visibleSweep}`} /><Stat label="Start policy" value={lab.visiblePolicy.Start ?? '—'} detail="greedy under visible values" /></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{VALUE_ITERATION_MDP.states.map((state) => { const value = lab.visibleValues[state]; const delta = value - lab.previousValues[state]; const terminal = VALUE_ITERATION_MDP.terminalStates.includes(state); return <div key={state} className={`rounded-lg border p-4 ${terminal ? 'border-emerald-300 bg-emerald-50' : 'border-slate-200 bg-white'}`}><div className="flex items-start justify-between"><div><strong className="text-slate-950">{state}</strong><p className="text-xs text-slate-500">{terminal ? 'terminal' : `policy: ${lab.visiblePolicy[state]}`}</p></div><span className="text-2xl font-black">{value.toFixed(3)}</span></div><p className={`mt-3 text-xs font-bold ${delta >= 0 ? 'text-emerald-700' : 'text-rose-700'}`}>Δ {delta >= 0 ? '+' : ''}{delta.toFixed(3)}</p></div>; })}</section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="text-sm font-black uppercase tracking-wide text-slate-600">Residual shrinking across sweeps</h3><div className="mt-4 flex h-40 items-end gap-1 overflow-x-auto">{lab.history.slice(0, 21).map((row) => { const height = Math.max(3, Math.min(100, 18 * Math.log10(1 + row.residual * 10))); return <div key={row.iteration} title={`sweep ${row.iteration}: ${row.residual}`} className="min-w-5 flex-1 rounded-t bg-indigo-500" style={{ height: `${height}%` }} />; })}</div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>sweep 0</span><span>toward Bellman fixed point</span></div></section>
    <section className="grid gap-4 lg:grid-cols-[1fr_0.9fr]"><div className="rounded-lg border border-indigo-200 bg-indigo-50 p-5 text-sm leading-6 text-indigo-950"><strong className="block text-xs uppercase tracking-wide text-indigo-700">Bellman optimality</strong><div className="mt-3 font-mono">V*(s) = maxₐ Σₛ′ P(s′|s,a)[r + γV*(s′)]</div><p className="mt-3">Convergence means another optimality backup barely changes the table; it is not an arbitrary number of sweeps.</p></div><div className="rounded-lg border border-rose-300 bg-rose-50 p-5 text-sm leading-6 text-rose-950"><strong className="flex items-center gap-2 text-xs uppercase tracking-wide text-rose-700"><AlertTriangle size={15} /> terminal-state bug fixed</strong><p className="mt-3">Paying +10 once when entering Goal gives <strong>{lab.terminalComparison.rewardOnEntry}</strong>. A +10 self-loop at Goal with γ={gamma.toFixed(2)} would instead imply value <strong>{lab.terminalComparison.repeatedSelfLoopValue.toFixed(2)}</strong>. Those are different MDPs.</p></div></section>
    <section className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm leading-6 text-emerald-950"><CheckCircle2 size={16} className="mr-2 inline" />Final Bellman residual {lab.residual.toExponential(2)}; policy Start→{lab.policy.Start}, Bridge→{lab.policy.Bridge}, Trap→{lab.policy.Trap}.</section><button type="button" onClick={() => { setGamma(VALUE_ITERATION_DEFAULTS.gamma); setTolerance(VALUE_ITERATION_DEFAULTS.tolerance); setVisibleSweeps(VALUE_ITERATION_DEFAULTS.visibleSweeps); }} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-bold"><RefreshCw size={16} /> Reset</button><div className="rounded-lg bg-slate-950 p-4 font-mono text-sm text-slate-100"><Sigma size={15} className="mr-2 inline" />residual = maxₛ |(T*V)(s) − V(s)|</div><AssessmentPanel lessonId="value-iteration" title="Value iteration check" />
  </div>;
}
