function validateGamma(gamma) { if (!Number.isFinite(gamma) || gamma < 0 || gamma >= 1) throw new RangeError('gamma must be in [0, 1) for this solver'); }
export function validateMdp(model) { if (!model || !Array.isArray(model.states) || !model.actions) throw new TypeError('invalid MDP model'); const states = new Set(model.states); const terminals = new Set(model.terminalStates ?? []); for (const terminal of terminals) { if (!states.has(terminal)) throw new RangeError(`unknown terminal state ${terminal}`); if (model.actions[terminal] && Object.keys(model.actions[terminal]).length > 0) throw new RangeError(`terminal state ${terminal} must not expose actions`); } for (const [state, actions] of Object.entries(model.actions)) { if (!states.has(state)) throw new RangeError(`unknown state ${state}`); for (const [actionId, transitions] of Object.entries(actions)) { const total = transitions.reduce((sum, transition) => sum + transition.probability, 0); if (transitions.length === 0 || transitions.some((transition) => !states.has(transition.to) || !Number.isFinite(transition.reward) || !Number.isFinite(transition.probability) || transition.probability < 0)) throw new RangeError(`invalid transitions for ${state}/${actionId}`); if (Math.abs(total - 1) > 1e-9) throw new RangeError(`${state}/${actionId} probabilities must sum to one`); } } return true; }
export function zeroValues(model) { return Object.fromEntries(model.states.map((state) => [state, 0])); }
export function actionValue(model, state, actionId, values, gamma) { validateGamma(gamma); const transitions = model.actions[state]?.[actionId]; if (!transitions) throw new RangeError(`unknown action ${state}/${actionId}`); return transitions.reduce((sum, transition) => sum + transition.probability * (transition.reward + gamma * values[transition.to]), 0); }
export function bellmanBackup(model, state, values, gamma) { validateGamma(gamma); if ((model.terminalStates ?? []).includes(state)) return { value: 0, actionId: null, actionValues: [] }; const actions = Object.keys(model.actions[state] ?? {}); if (actions.length === 0) throw new RangeError(`non-terminal state ${state} has no actions`); const actionValues = actions.map((actionId) => ({ actionId, value: actionValue(model, state, actionId, values, gamma) })); const best = actionValues.reduce((current, candidate) => candidate.value > current.value ? candidate : current, actionValues[0]); return { value: best.value, actionId: best.actionId, actionValues }; }
export function synchronousSweep(model, values, gamma) { validateMdp(model); const next = {}; let residual = 0; for (const state of model.states) { const backup = bellmanBackup(model, state, values, gamma); next[state] = backup.value; residual = Math.max(residual, Math.abs(next[state] - values[state])); } return { values: next, residual }; }
export function extractGreedyPolicy(model, values, gamma) { return Object.fromEntries(model.states.map((state) => [state, bellmanBackup(model, state, values, gamma).actionId])); }
export function bellmanResidual(model, values, gamma) { let residual = 0; for (const state of model.states) residual = Math.max(residual, Math.abs(bellmanBackup(model, state, values, gamma).value - values[state])); return residual; }
export function runValueIteration(model, gamma, tolerance = 1e-6, maxIterations = 1000) { validateMdp(model); validateGamma(gamma); if (!Number.isFinite(tolerance) || tolerance <= 0) throw new RangeError('tolerance must be positive'); if (!Number.isInteger(maxIterations) || maxIterations <= 0) throw new RangeError('maxIterations must be positive'); let values = zeroValues(model); const history = [{ iteration: 0, values, residual: bellmanResidual(model, values, gamma) }]; let converged = false; for (let iteration = 1; iteration <= maxIterations; iteration += 1) { values = synchronousSweep(model, values, gamma).values; const residual = bellmanResidual(model, values, gamma); history.push({ iteration, values, residual }); if (residual <= tolerance) { converged = true; break; } } return { values, policy: extractGreedyPolicy(model, values, gamma), history, converged, residual: history[history.length - 1].residual }; }
export function terminalRewardComparison(reward, gamma) { if (!Number.isFinite(reward)) throw new TypeError('reward must be finite'); if (!Number.isFinite(gamma) || gamma < 0 || gamma > 1) throw new RangeError('gamma must be in [0, 1]'); return { rewardOnEntry: reward, repeatedSelfLoopValue: gamma === 1 ? Number.POSITIVE_INFINITY : reward / (1 - gamma) }; }
export function buildValueIterationLab({ model, gamma, tolerance, maxIterations, visibleSweeps }) { const solution = runValueIteration(model, gamma, tolerance, maxIterations); const clampedSweep = Math.max(0, Math.min(visibleSweeps, solution.history.length - 1)); const visible = solution.history[clampedSweep]; const previous = solution.history[Math.max(0, clampedSweep - 1)]; return { ...solution, visibleSweep: clampedSweep, visibleValues: visible.values, visibleResidual: visible.residual, previousValues: previous.values, visiblePolicy: extractGreedyPolicy(model, visible.values, gamma), terminalComparison: terminalRewardComparison(10, gamma) }; }
